name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: GITNCLR/bastardkb-qmk
      qmk_ref: bkb-master

  reset-release:
    name: 'Delete existing release so timestamp updates'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Delete release "latest" if it exists
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete latest -y --repo "$GITHUB_REPOSITORY" || true

  update-tag:
    name: 'Update tag for release'
    runs-on: ubuntu-latest
    needs: reset-release
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Move or recreate "latest" tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -fa latest -m "Auto release for $GITHUB_SHA" $GITHUB_SHA
          git push -f origin refs/tags/latest

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
    if: always() && !cancelled()
    needs: update-tag

  retitle-release:
    name: 'Set release title & notes'
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Update release metadata
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release edit latest \
            --repo "$GITHUB_REPOSITORY" \
            --title "Noahâ€™s Charybdis 4x6 Layout"
